# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0d8b2d1ed63d50c6feb26d389de24ba58841c3de6e594c91077e4afef7c4573a95db734e315412c7c518cdba8f27cb931f7b91e91247bf2d4293604a4cb2281

test:
  secret_key_base: e77eb32edef1f791db806076406fb65a237e9f2f40c02deee3c43fd0bdb2e4169f64ce090869bac42b9742e95bb8df90864cf8afc09e396d0c0cf507fd8923fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
